### ISSUE TITLE
pod installation instructions

### ISSUE THREAD

**Issue by marcospolanco** [steve228uk/MessengerKit#2]
What worked for me was:

`pod 'MessengerKit', :git => 'https://github.com/steve228uk/MessengerKit.git'
`

The current instructions result in my case with:

>      git@github.com: Permission denied (publickey).
     fatal: Could not read from remote repository.
     
     Please make sure you have the correct access rights
     and the repository exists.

**Comment by steve228uk** [comment]
Hi @marcospolanco,

It looks like this is an issue with your publickey on Github. You can take a look at how to resolve this issue here: https://help.github.com/articles/error-permission-denied-publickey/

I will however update the readme to use http as it's likely that others will encounter this issue.

Thanks! 👍
